language: node_js
node_js: "0.12"
env:
  global:
    secure: "HmOAYGJuHc1PmqTSoGsmC3RLgLCKGkz4+by7ZN0YkX2CmWlc3G2jtiJ5VIq40YVtzlo0oi+nphFMOdWdiyjXG6zezbPwVIxlijg7xcGvmXDVYe75mWNqW3sVnF4M8YLMMMyfyMcrlkOJdV9rV67aqFM1bE0z8PLgELwqgmcVw/A="
before_install:
  - ./ci/create-sencha-environment.sh
install:
  - npm install
  - gem install jsduck
script:
  - npm test
  - ./ci/create-sencha-package.sh
after_success:
  - npm run-script coveralls
  - ./ci/update-gh-pages.sh
branches:
  only:
    - master
cache:
  directories:
    - __download
    - __install
    - node_modules
